apiVersion: v1
kind: Pod
metadata:
  name: demo-hostpath-volume
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-hostpath-volume
    volumeMounts:
    - mountPath: /test-dir
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp/demo-hostpath-kub
      # this field is optional
      type: Directory
      #type: DirectoryOrCreate
